name: docker-compose
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start the stack
        run: docker-compose up --build -d
        env:
          EXPERIMENT: getuigenverhalen
      - name: Wait for services
        run: sleep 30
      - name: Test if server is up
        run: docker-compose ps server | grep Up
      - name: Test if elasticsearch is up
        run: docker-compose ps elasticsearch | grep Up        
      - name: Test if usercreator exited successfully
        run: docker-compose ps usercreator | grep 'Exit 0'
      - name: Test if indexer exited successfully
        run: docker-compose ps indexer | grep 'Exit 0'        
      - name: Test if the UI is accessible
        run: curl --show-error --retry 10 --retry-connrefused http://0.0.0.0:8080/
